### ISSUE TITLE
Handling stale/changed data in UI

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/ngx-dashboard#121]
The goal of this issue is to start a discussion about 1) how we can address this and 2) identify events that should be handled.

**Problem**: With the move to Angular, we no longer have an Ember-data-like feature to handle updating data in the UI that has changed by other means.  This was discussed in the context of sharing (https://github.com/whole-tale/ngx-dashboard/pull/16#issuecomment-729154698), but is also apparent in other areas as well.  As I recall from a dev meeting, one way to handle this is to use the notification stream to inform the UI of changes. Currently, it often requires a complete refresh of the page:

I am aware of the following:
* When a tale is shared with me, it does not appear on the Tales page. This is probably the case when a tale is made public by another user
* When another user makes changes to workspace, external data,  tale metadata, creates a version, etc. these changes are not reflected in my UI without refresh.
* When I import a tale (e.g., from Zenodo), the initial tale is created but the resulting imported data is not reflected without refresh
* ...?

**Comment by bodom0015** [comment]
I should note that this is not a case that Ember Data handles: synchronizing data between two different clients

Ember Data handled the case of having a single data store within each instance of the client. For example, if we edit the Tale name via changing metadata it would update that Tale's name in the catalog view as well. This does not mean that changing the name in one client would propagate the change to another client.

To enable this type of synchronized behavior, we would need to take advantage of Girder's SSE system to propagate custom resource updates to the client. With our above example, when a Tale's name changes in the backend we could send an event called "tale-updated" or similar, and optionally include the new metadata to avoid immediately being queried by all clients simultaneously.

**Comment by craig-willis** [comment]
Looking at how to implement this on the backend, I think we can simply create a notification for each event we're interested in, as we already do with the jobs:

https://github.com/whole-tale/girder_wholetale/blob/master/server/utils.py#L64-L65

Since the Girder `createNotification()` method requires a `user`, unless I've missed something we'd need to iterate over every affected user and send a separate notification. 

I see a few a few broad categories of events:  events that affect my UI state, events that affect users of a shared tale, and global events that affect everyone on the system (least important).

Events that affect my UI state are typically jobs, so these may already be handled through existing notifications. However, the tale import case is one of my examples above of how the UI state is stale (registered data isn't populated without refresh), but the notification may already be there to do so.
* Instance started (wt_create_instance) is already used by the interact tab (I think)
* Instance image updated (wt_update_instance) may already be used by interact tab 
* Git import complete (wt_git_import) could affect files tab
* Image build complete (wt_build_image) could be used to tell the user they can restart
* Dataset registration complete (wt_register_data) could affect data modal
* Tale import complete (wholetale.import_tale, wholetale.import_binder) could affect metadata, registered data, files
* ...?

Several of the above events would also affect users of a shared tale (git import, image build (possibly), dataset registration, tale import). Additionally:
* Tale shared/unshared with me or deleted would determine if a tale appears on "Shared with Me"
* Dataset added/removed from tale would change the external data view
* File/folder added/removed from tale would change the file view
* Tale metadata changed 
* Version added/removed changes the version history
* Run added/removed changes the version history
* Version restored changes (possibly) external data, files, metadata, etc.
* ...

Global events are maybe less important but worth noting:
* Tale public flag set/removed (would appear in tale catalog)
* Dataset registered (would appear in data catalog)

Any thoughts/corrections welcome.

**Comment by bodom0015** [comment]
This looks great! This looks extremely thorough and well though out.

One case that may have been missed is the Tale image build logs from repo2docker, but we would probably need to consider send these log messages in bulk, instead of sending thousands of updates one line at a time.

The few places in the Angular dashboard where we currently poll for updates:
* Run Tale Button: [Poll for Instance status changes, update button text and state](https://github.com/whole-tale/ngx-dashboard/blob/master/src/app/tales/components/tale-run-button/tale-run-button.component.ts#L44-L91)
* Publish Tale modal: [Poll Job for job status, update latest publish info](https://github.com/whole-tale/ngx-dashboard/tree/master/src/app/%2Brun-tale/run-tale/modals/publish-tale-dialog/publish-tale-dialog.component.ts#L83-L177)
* View Logs modal: [Poll Job for job logs, display latest logs, optionally scroll to bottom](https://github.com/whole-tale/ngx-dashboard/blob/master/src/app/layout/notification-stream/modals/view-logs-dialog/view-logs-dialog.component.ts)


Noting that in the Ember dashboard, the polling code was conveniently centralized to a single method: https://github.com/whole-tale/dashboard/blob/master/app/services/api-call.js#L493. This definitely would be a good pattern to adopt on the Angular side as well.

**Comment by craig-willis** [comment]
Thanks @bodom0015. The draft PR is https://github.com/whole-tale/girder_wholetale/pull/445.  Any initial feedback welcome, since I'll likely use this same approach for all events we're interested in.
