### ISSUE TITLE
[Draft] Create/edit run configuration

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/ngx-dashboard#122]
Revised based on 6/14/21 dev call

**Requirements:**
* A tale has a single default run configuration (see https://github.com/whole-tale/girder_wholetale/issues/492)
* The user can edit the run configuration (i.e., the entrypoint script, test script)
* ~A tale can have multiple run configurations~
* ~The user can add, edit, rename, configurations~ The
* A run configuration consists of a name, the path to an entrypoint script (required) and test script (optional). (Note: "type" in the mockups will not be supported and can be ignored).

**Mockups:**
Mockups for this feature are incomplete. There is one from @hategan's proof-of-concept and another partial mockup.
* [Versioning / Recorded Run UI presentation](https://docs.google.com/presentation/d/1nf1aCd7M2ONVGLDR3AcMMIYb4cOsfF1WZeRE9JYfpSY/edit#slide=id.g6d71547ac5_0_39) slide 6. 
* [Recorded Run Mockup](https://whole-tale.github.io/wholetale-css-mockup/src/run-meta.html) -- Edit configuration UI is not defined.

**Comment by hategan** [comment]
> * Note: "type" in the mockups will not be supported and can be ignored.

Maybe this is referring to an initial iteration, but, in my opinion, supporting at least local and container are important to allow a decent development workflow. The idea being that "local" allows uses to quickly invoke an executable for testing purposes and rapid prototyping, but provides little guarantees of reproducibility, whereas "container" involves building a container from scratch, which is not suitable for rapid prototyping since it tends to take a long time, but essential for reproducibility.
