### ISSUE TITLE
Involatile data on metadata page has broken links

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/ngx-dashboard#23]
**Steps to Reproduce**
1. Deploy and register LIGO
1. Navigate to View > Metadata
1. Click on any file in `Involatile Data` 

**Expected Results**
File should download 

**Actual Results**
Link points to `https://dashboard.local.wholetale.org/null`

**Comment by bodom0015** [comment]
Following the same pattern from the legacy dashboard, as of #77 we are using Girder's item/:id/download endpoint to download these files. This endpoint returns a 303 redirect to the file's original location.

This can apparently break for particular types of files that the browser can display natively, which do not appear to be downloaded by default - for example, see the BBH_events_v3.json from the LIGO Tutorial Tale. I believe that sending the contentDisposition=attached parameter is supposed to tell Girder to download the item instead of redirecting to it, but I don't think that this parameter is currently being respected?

@Xarthisius have you noticed this odd behavior with the Item download endpoint?
