### ISSUE TITLE
Add support for uploading folders

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/ngx-dashboard#233]
This is something we've heard before and reinforced by one of our verification evaluation users.

**Problem**
The dashboard currently only allows users to upload files. If users have complex folder structures, they must manually create the structures and upload files per folder (or alternatively upload a single zipfile and unzip it using one of the IDEs).

**Proposed solution**
Enhance dashboard to allow users to upload a folder and all contents with a single selection.

**Comment by craig-willis** [comment]
Nudging this issue. Looking through feedback from verification supplement users, this came up a few times.

**Comment by bodom0015** [comment]
Looking into some options/measures here:

1. (Chrome Only?) Upload the files contained in a folder hierarchy as a flat list (Effort: Minimal)
Since we already allow multi-file upload (e.g. select 3 files for upload), we already have a queue mechanism in place to handle this case. Simply adding a few new attributes (`directory webkitdirectory mozdirectory`) allows the user a simple way to select a folder in the file upload prompt.
See https://stackoverflow.com/questions/20429960/file-upload-and-knowing-the-directory-structure

2. (Chrome Only?) Upload a folder, and also maintain directory structure (Effort: Medium)
By enabling the above, a folder will be uploaded as a flat list of files. What we do with this list of files is up to us. Currently, we loop over the selected files in the queue and upload the file chunks. We could add a step here to parse the `webkitRelativePath` attribute and create the containing folder structure. We also expect that the user is uploading the files to the currently selected folder, so some work would be needed to undo this assumption or abstract the existing code. A keen eye would also notice the `webkit` part of the above, meaning that this pattern likely only works for webkit-based browsers such as Chrome or Opera.
See http://sapphion.com/2012/06/12/keep-directory-structure-when-uploading/

3. DropzoneJS or similar (Effort: Medium)
Some seasoned library, such as DropzoneJS would likely be the best solution here in terms of ease of implementation and maturity/support for offered features. My understanding is that this pattern would work in browsers that aren't Chrome, which is a plus. Since any "structured" upload would force us to rework our current pattern for handling file uploads anyways, we could take that as an opportunity to use something like ngx-dropzone or ngx-dropzone-wrapper using our existing chunk upload logic as a basis.
See https://stackoverflow.com/a/42693689
