### ISSUE TITLE
Initial tale's author field is not following the schema

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/ngx-dashboard#32]
**Steps to Reproduce**
1. Deploy and create a new Tale
1. Navigate to the new Tale's *View* > *Metadata*. Click *Edit*
1. Add a description.
1. Hit Save

**Expected Results**
Tale updates.

**Actual Results**
Tale fails to update.

**NOTES**
Looks like initially the Tale is created with `authors: ["Kacper Kowalik"]`, which is not following scheme. As a result PUT is bounced with 400 from the backend.

**Comment by bodom0015** [comment]
I am seeing similar behavior, but it seems for a different reason? My PUT was returning 400 because `null` was provided as a value for some boolean fields. POST seemed fine with this, but PUT complained which was odd.

I've adjusted the `create-tale-modal` to add more sensible defaults for some of the fields, such as `description` which has been a problem in the past.
