### ISSUE TITLE
Public/My Tales filter resets after navigation

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/ngx-dashboard#36]
**Steps to Reproduce**
1.  Select Dashboard > My Tales
2. View a tale
3. Select "Return to Dashboard"

**Expected Results**
Dashboard displays with "My Tales" selected

**Actual Results**
Dashboard displays with "Public Tales" selected

**NOTES**
I think the implementation on the old Dashboard happened later in the v0.9 release, so this may not really be a bug.

**Comment by bodom0015** [comment]
Good catch! It seems the browser's "Back" button works as intended and navigates you back to the proper view. The "Return to Dashboard" button in the ui, however, is a hard-coded link to `/public`.

This inconsistency can be corrected by making "Return to Dashboard" navigate backwards using something akin to `window.history.back()`.

**Comment by bodom0015** [comment]
So this one turns out to be a bit of a curious case.

Switching tabs on the Run view appears to count as a route navigation (this is likely a bug). So when we call `window.history.back()`, it may not actually bring us back to the Tale Dashboard. This may require revisiting the Run view's routes to make them a bit more friendly.

Alternatively, the public/mine views may be reworked so that they are not entirely separate views (since they share code, and probably shouldn't be separated anyways)
