### ISSUE TITLE
No "Create New Tale and Launch" option

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/ngx-dashboard#51]
**Steps to Reproduce**
1. Select create new tale
2. Note missing "Create New Tale and Launch" option

**Expected Results**
"Create New Tale and Launch" option is present. Selecting it creates the new tale and runs it, redirecting to the interact tab (per current system and test plan)

**Actual Results**
Option isn't there.

**NOTES**
@xarthisius has long disliked the "Create and Launch", so this may have been intentional.  However, I don't recall making a final decision. Maybe we discuss here?

**Comment by bodom0015** [comment]
I know we discussed this at one point, and I thought I remember @Xarthisius saying that he got the PIs to agree on this? That was quite a long time ago tho, so I may be mistaken. 

For historical context, this view was created following the old mockups that did not factor in Create + Launch - I, thinking that this was an intentional shift in user workflow, left this functionality out of the Angular rewrite entirely. Upon sharing knowledge of the existing feature with Kristina, she created a new mockup that incorporated the Create + Launch [in a prettier way](https://whole-tale.github.io/wholetale-css-mockup/src/browse-mytales.html). Some time after this, there was some discussion of removing the feature entirely due to the complexity of the operation and the error-handling involved.

I am unclear where we left off after that discussion.. if there is still some desire to allow users the option to Create + Launch, we can propose and discuss some ways to improve that workflow here.

The first bit of complexity is that Create + Launch is two separate API operations that depend slightly on one another - we first create a Tale, and then we create an Instance associated with that Tale. Another (potential?) complication is that "Analyze in WT" has many many edge cases and its own complex workflow - adding the Create + Launch on top of AiWT exacerbates the issue, creating even more edge cases. Separating these operations out into explicit steps makes it much easier to catch errors from particular parts of the process.

For example, imagine the "worst" case of AiWT + Create + Launch: this is Tale Creation (synchronous) + Data Registration/Association (asynchronous) + Instance Creation (synchronous), which includes a Tale Build via repo2docker (asynchronous). While we may be saving the user a mouse click here and there, chaining operations together in this way makes it very difficult to handle errors using a sane pattern.

We've also discussed was to improve the notifications/error-handling previously in a Google Doc: https://docs.google.com/document/d/1IkvsZqxxlIBaxVLT1yb1kWtGyDuJRo8ZzT1hsqke_NE/edit

**Comment by craig-willis** [comment]
Notes from 9/21 dev call:
* Introduces technical complexity and instability in error handling
* Not clearly needed (not user requested)
* By default, launch may take a long time due to image builds
* User does need to make an extra click (and know they need to do so)
* CO requires users to launch Cloud Workstations, which also takes a long time. However, their UI has more features (JupyterLab based editor, etc).

Consensus is that we drop it for now and add it back if requested instead of adding it back now.
